name: Extract List of Supported Pruefis from Data
on:
  push:
    branches:
      - main
jobs:
  check:
    name: Analyse and Print Result
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run Extraction
        run: |
          python tooling/generate_list_of_supported_pruefidentifikators.py
