name: Generate AHB diffs via dependabot triggered by `ahlbatross` version bump.

on:
  pull_request:
    paths:
      - "requirements.txt"

jobs:
  update-if-dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install updated package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content
        run: |
          mkdir -p diff
          ahlbatross --output-dir diff

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add diff/
          if git diff --staged --quiet; then
            echo "no changes to commit"
          else
            git commit -m "update generated diff files for new ahlbatross release"
            git push
          fi
