name: Prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier
        run: npm install prettier

      # just runs a check; use for instance https://prettier.io/playground/ to fix formatting issues manually
      - name: Run Prettier check
        run: npx prettier --check . --ignore-path .prettierignore
