name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # fetch the actual content of Large File Storage tracked files instead of just the pointers

      - name: Set folder name from commit message
        id: set-folder
        run: |
          FOLDER_NAME=$(echo "${{ github.event.head_commit.message }}" | grep -o 'FV[0-9]\{4\}')
          echo "FOLDER_NAME=${FOLDER_NAME}" >> $GITHUB_ENV

      - name: Upload JSON files to Azure Blob Storage
        if: env.FOLDER_NAME != ''
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ${{ env.FOLDER_NAME }}
          container_name: ahb-tables
          connection_string: ${{ secrets.AzureBlobStorageConnectionString }}
          extra_args: "--pattern *.json --destination-path ${{ env.FOLDER_NAME }}"
          overwrite: "true"

      - name: Upload XLSX files to Azure Blob Storage
        if: env.FOLDER_NAME != ''
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ${{ env.FOLDER_NAME }}
          container_name: ahb-tables
          connection_string: ${{ secrets.AzureBlobStorageConnectionString }}
          extra_args: "--pattern *.xlsx --destination-path ${{ env.FOLDER_NAME }}"
          overwrite: "true"

      - name: Upload CSV files to Azure Blob Storage
        if: env.FOLDER_NAME != ''
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ${{ env.FOLDER_NAME }}
          container_name: ahb-tables
          connection_string: ${{ secrets.AzureBlobStorageConnectionString }}
          extra_args: "--pattern *.csv --destination-path ${{ env.FOLDER_NAME }}"
          overwrite: "true"
