name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload JSON files to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: .  # This is the root directory of the repository
          container_name: ahb-tables
          connection_string: ${{ secrets.AzureBlobStorageConnectionString }}
          extra_args: '--pattern *.json'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'

      - name: Upload XLSX files to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: .  # This is the root directory of the repository
          container_name: ahb-tables
          connection_string: ${{ secrets.AzureBlobStorageConnectionString }}
          extra_args: '--pattern *.xlsx'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'

      - name: Upload CSV files to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: .  # This is the root directory of the repository
          container_name: ahb-tables
          connection_string: ${{ secrets.AzureBlobStorageConnectionString }}
          extra_args: '--pattern *.csv'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'